# mplPars = {'text.usetex': True,
#            'axes.labelsize': 'large',
#            'axes.titlesize': 24,
#            'font.family': 'sans-serif',
#            'font.sans-serif': 'computer modern roman',
#            'font.size': 24,
#            'font.weight': 'black',
#            'xtick.labelsize': 20,
#            'ytick.labelsize': 20,
#            'legend.fontsize': 20,
#            'legend.frameon': True,
#            'legend.framealpha': 0,
#            'legend.fancybox': True,
#            'text.latex.preamble': r'\usepackage{cmbright}'
#            }

mplPars = {'axes.labelsize': 'large',
           'axes.titlesize': 24,
           'font.family': 'sans-serif',
           'font.sans-serif': 'computer modern roman',
           'font.size': 24,
           'font.weight': 'black',
           'xtick.labelsize': 20,
           'ytick.labelsize': 20,
           'legend.fontsize': 20,
           'legend.frameon': True,
           'legend.framealpha': 0,
           'legend.fancybox': True,
           }
